export const ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART' = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART' = 'REMOVE_PRODUCT_FROM_CART'

export const CLEAR_CART: 'CLEAR_CART' = 'CLEAR_CART'

export const INCREMENT_PRODUCT_COUNT: 'INCREMENT_PRODUCT_COUNT' = 'INCREMENT_PRODUCT_COUNT'
export const DECREMENT_PRODUCT_COUNT: 'DECREMENT_PRODUCT_COUNT' = 'DECREMENT_PRODUCT_COUNT'

export const FILL_CART: 'FILL_CART' = 'FILL_CART'